apiVersion: v1
kind: Namespace
metadata:
  name: ns-danilo-sepulveda

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-danilo-sepulveda
  namespace: ns-danilo-sepulveda
data:
  AMBIENTE: "produccion"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-danilo-sepulveda
  namespace: ns-danilo-sepulveda
type: Opaque
stringData:
  API_KEY: "danilo-sepulveda"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-danilo-sepulveda
  namespace: ns-danilo-sepulveda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-danilo-sepulveda
  template:
    metadata:
      labels:
        app: app-danilo-sepulveda
    spec:
      containers:
        - name: app-danilo-sepulveda
          image: danilosepulvedaf/tarea-final:danilo-sepulveda
          ports:
            - containerPort: 3000
          env:
            - name: AMBIENTE
              valueFrom:
                configMapKeyRef:
                  name: config-danilo-sepulveda
                  key: AMBIENTE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-danilo-sepulveda
                  key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: svc-danilo-sepulveda
  namespace: ns-danilo-sepulveda
spec:
  selector:
    app: app-danilo-sepulveda
  ports:
    - port: 80
      targetPort: 3000
